In [ ]:
!mamba install bs4==4.10.0 -y
!mamba install html5lib==1.1 -y

In [ ]:
from bs4 import BeautifulSoup
import html5lib
import requests
import pandas as pd

## Extract Data Using Web Scraping

### Webpage Contents

Gather the contents of the webpage in text format using the `requests` library and assign it to the variable <code>html_data</code>

The wikipedia webpage https://web.archive.org/web/20200318083015/https://en.wikipedia.org/wiki/List_of_largest_banks provides information about largest banks in the world by various parameters. Scrape the data from the table 'By market capitalization' and store it in a JSON file.

In [ ]:
import json
import requests
from bs4 import BeautifulSoup

url = 'https://web.archive.org/web/20200318083015/https://en.wikipedia.org/wiki/List_of_largest_banks'
response = requests.get(url)

if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser')
    table = soup.find('table', {'class': 'wikitable'})
    data_list = [{'Bank Name': td[0].text.strip(), 'Market Cap': td[1].text.strip()} for td in
                 [row.find_all('td') for row in table.find_all('tr')[1:]] if len(td) >= 2]

    with open('largest_banks.json', 'w') as json_file:
        json.dump(data_list, json_file, indent=4)

    html_data = response.text
else:
    print("Failed to retrieve the webpage")

In [ ]:
data_list

[{'Bank Name': '1', 'Market Cap': 'Industrial and Commercial Bank of China'},
 {'Bank Name': '2', 'Market Cap': 'China Construction Bank'},
 {'Bank Name': '3', 'Market Cap': 'Agricultural Bank of China'},
 {'Bank Name': '4', 'Market Cap': 'Bank of China'},
 {'Bank Name': '5', 'Market Cap': 'Mitsubishi UFJ Financial Group'},
 {'Bank Name': '6', 'Market Cap': 'HSBC Holdings PLC'},
 {'Bank Name': '7', 'Market Cap': 'JPMorgan Chase'},
 {'Bank Name': '8', 'Market Cap': 'Bank of America'},
 {'Bank Name': '9', 'Market Cap': 'BNP Paribas'},
 {'Bank Name': '10', 'Market Cap': 'Crédit Agricole'},
 {'Bank Name': '11', 'Market Cap': 'Citigroup Inc.'},
 {'Bank Name': '12', 'Market Cap': 'Japan Post Bank'},
 {'Bank Name': '13', 'Market Cap': 'Wells Fargo'},
 {'Bank Name': '14', 'Market Cap': 'Sumitomo Mitsui Financial Group'},
 {'Bank Name': '15', 'Market Cap': 'Mizuho Financial Group'},
 {'Bank Name': '16', 'Market Cap': 'Banco Santander'},
 {'Bank Name': '17', 'Market Cap': 'Deutsche Bank'},
 {'Bank Name': '18', 'Market Cap': 'Société Générale'},
 {'Bank Name': '19', 'Market Cap': 'Groupe BPCE'},
 {'Bank Name': '20', 'Market Cap': 'Barclays'},
 {'Bank Name': '21', 'Market Cap': 'Bank of Communications'},
 {'Bank Name': '22', 'Market Cap': 'Postal Savings Bank of China'},
 {'Bank Name': '23', 'Market Cap': 'Royal Bank of Canada'},
 {'Bank Name': '24', 'Market Cap': 'Lloyds Banking Group'},
 {'Bank Name': '25', 'Market Cap': 'ING Group'},
 {'Bank Name': '26', 'Market Cap': 'Toronto-Dominion Bank'},
 {'Bank Name': '27', 'Market Cap': 'China Merchants Bank'},
 {'Bank Name': '28', 'Market Cap': 'Crédit Mutuel'},
 {'Bank Name': '29', 'Market Cap': 'Norinchukin Bank'},
 {'Bank Name': '30', 'Market Cap': 'UBS'},
 {'Bank Name': '31', 'Market Cap': 'Industrial Bank (China)'},
 {'Bank Name': '32', 'Market Cap': 'UniCredit'},
 {'Bank Name': '33', 'Market Cap': 'Goldman Sachs'},
 {'Bank Name': '34', 'Market Cap': 'Shanghai Pudong Development Bank'},
 {'Bank Name': '35', 'Market Cap': 'Intesa Sanpaolo'},
 {'Bank Name': '36', 'Market Cap': 'Royal Bank of Scotland Group'},
 {'Bank Name': '37', 'Market Cap': 'China CITIC Bank'},
 {'Bank Name': '38', 'Market Cap': 'China Minsheng Bank'},
 {'Bank Name': '39', 'Market Cap': 'Morgan Stanley'},
 {'Bank Name': '40', 'Market Cap': 'Scotiabank'},
 {'Bank Name': '41', 'Market Cap': 'Credit Suisse'},
 {'Bank Name': '42', 'Market Cap': 'Banco Bilbao Vizcaya Argentaria'},
 {'Bank Name': '43', 'Market Cap': 'Commonwealth Bank'},
 {'Bank Name': '44', 'Market Cap': 'Standard Chartered'},
 {'Bank Name': '45', 'Market Cap': 'Australia and New Zealand Banking Group'},
 {'Bank Name': '46', 'Market Cap': 'Rabobank'},
 {'Bank Name': '47', 'Market Cap': 'Nordea'},
 {'Bank Name': '48', 'Market Cap': 'Westpac'},
 {'Bank Name': '49', 'Market Cap': 'China Everbright Bank'},
 {'Bank Name': '50', 'Market Cap': 'Bank of Montreal'},
 {'Bank Name': '51', 'Market Cap': 'DZ Bank'},
 {'Bank Name': '52', 'Market Cap': 'National Australia Bank'},
 {'Bank Name': '53', 'Market Cap': 'Danske Bank'},
 {'Bank Name': '54', 'Market Cap': 'State Bank of India'},
 {'Bank Name': '55', 'Market Cap': 'Resona Holdings'},
 {'Bank Name': '56', 'Market Cap': 'Commerzbank'},
 {'Bank Name': '57', 'Market Cap': 'Sumitomo Mitsui Trust Holdings'},
 {'Bank Name': '58', 'Market Cap': 'Ping An Bank'},
 {'Bank Name': '59', 'Market Cap': 'Canadian Imperial Bank of Commerce'},
 {'Bank Name': '60', 'Market Cap': 'U.S. Bancorp'},
 {'Bank Name': '61', 'Market Cap': 'CaixaBank'},
 {'Bank Name': '62', 'Market Cap': 'Truist Financial'},
 {'Bank Name': '63', 'Market Cap': 'ABN AMRO Group'},
 {'Bank Name': '64', 'Market Cap': 'KB Financial Group Inc'},
 {'Bank Name': '65', 'Market Cap': 'Shinhan Bank'},
 {'Bank Name': '66', 'Market Cap': 'Sberbank of Russia'},
 {'Bank Name': '67', 'Market Cap': 'Nomura Holdings'},
 {'Bank Name': '68', 'Market Cap': 'DBS Bank'},
 {'Bank Name': '69', 'Market Cap': 'Itaú Unibanco'},
 {'Bank Name': '70', 'Market Cap': 'PNC Financial Services'},
 {'Bank Name': '71', 'Market Cap': 'Huaxia Bank'},
 {'Bank Name': '72', 'Market Cap': 'Nonghyup Bank'},
 {'Bank Name': '73', 'Market Cap': 'Capital One'},
 {'Bank Name': '74', 'Market Cap': 'Bank of Beijing'},
 {'Bank Name': '75', 'Market Cap': 'The Bank of New York Mellon'},
 {'Bank Name': '76', 'Market Cap': 'Banco do Brasil'},
 {'Bank Name': '77', 'Market Cap': 'Hana Financial Group'},
 {'Bank Name': '78', 'Market Cap': 'OCBC Bank'},
 {'Bank Name': '79', 'Market Cap': 'Banco Bradesco'},
 {'Bank Name': '80', 'Market Cap': 'Handelsbanken'},
 {'Bank Name': '81', 'Market Cap': 'Caixa Econômica Federal'},
 {'Bank Name': '82', 'Market Cap': 'KBC Bank'},
 {'Bank Name': '83', 'Market Cap': 'China Guangfa Bank'},
 {'Bank Name': '84', 'Market Cap': 'Nationwide Building Society'},
 {'Bank Name': '85', 'Market Cap': 'Woori Bank'},
 {'Bank Name': '86', 'Market Cap': 'DNB ASA'},
 {'Bank Name': '87', 'Market Cap': 'SEB Group'},
 {'Bank Name': '88', 'Market Cap': 'Bank of Shanghai'},
 {'Bank Name': '89', 'Market Cap': 'United Overseas Bank'},
 {'Bank Name': '90', 'Market Cap': 'Bank of Jiangsu'},
 {'Bank Name': '91', 'Market Cap': 'La Banque postale'},
 {'Bank Name': '92', 'Market Cap': 'Landesbank Baden-Württemberg'},
 {'Bank Name': '93', 'Market Cap': 'Erste Group'},
 {'Bank Name': '94', 'Market Cap': 'Industrial Bank of Korea'},
 {'Bank Name': '95', 'Market Cap': 'Qatar National Bank'},
 {'Bank Name': '96', 'Market Cap': 'Banco Sabadell'},
 {'Bank Name': '97', 'Market Cap': 'Swedbank'},
 {'Bank Name': '98', 'Market Cap': 'BayernLB'},
 {'Bank Name': '99', 'Market Cap': 'State Street Corporation'},
 {'Bank Name': '100', 'Market Cap': 'China Zheshang Bank'},
 {'Bank Name': '101', 'Market Cap': 'Bankia'}]

In [ ]:
# html_data[760:783]

### Scraping the Data

<b> Question 2</b> Using the contents and `beautiful soup` load the data from the `By market capitalization` table into a `pandas` dataframe. The dataframe should have the bank `Name` and `Market Cap (US$ Billion)` as column names.  Display the first five rows using head.

In [ ]:
#Replace the dots below
# soup="......"



import pandas as pd
from bs4 import BeautifulSoup

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(html_data, 'html.parser')

# Find the table with the desired data (By market capitalization)
table = soup.find('table', {'class': 'wikitable'})

# Initialize an empty list to store the data
data_list = []

# Iterate through the rows of the table
for row in table.find_all('tr')[1:]:  # Skip the header row
    columns = row.find_all('td')
    if len(columns) >= 2:  # Ensure that there are at least 2 columns with data
        bank_name = columns[0].text.strip()
        market_cap = columns[1].text.strip()
        data_list.append({'Bank Name': bank_name, 'Market Cap (US$ Billion)': market_cap})

# Create a Pandas DataFrame from the scraped data
df = pd.DataFrame(data_list)

# Display the first five rows using head
print(df.head())

  Bank Name                 Market Cap (US$ Billion)
0         1  Industrial and Commercial Bank of China
1         2                  China Construction Bank
2         3               Agricultural Bank of China
3         4                            Bank of China
4         5           Mitsubishi UFJ Financial Group


### Loading the Data

Load the `pandas` dataframe created above into a JSON named `bank_market_cap.json` using the `to_json()` function.

In [ ]:
# Save the DataFrame to a JSON file
df.to_json('bank_market_cap.json', orient='records', lines=True)
df

    Bank Name                 Market Cap (US$ Billion)
0           1  Industrial and Commercial Bank of China
1           2                  China Construction Bank
2           3               Agricultural Bank of China
3           4                            Bank of China
4           5           Mitsubishi UFJ Financial Group
..        ...                                      ...
96         97                                 Swedbank
97         98                                 BayernLB
98         99                 State Street Corporation
99        100                      China Zheshang Bank
100       101                                   Bankia

[101 rows x 2 columns]